libro:
    pattern:  /
    defaults: { _controller: "PMLibroBundle:Libro:index" }

libro_show:
    pattern:  /{id}/show
    defaults: { _controller: "PMLibroBundle:Libro:show" }

libro_new:
    pattern:  /new
    defaults: { _controller: "PMLibroBundle:Libro:new" }

libro_create:
    pattern:  /create
    defaults: { _controller: "PMLibroBundle:Libro:create" }
    requirements: { _method: post }

libro_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PMLibroBundle:Libro:edit" }

libro_update:
    pattern:  /{id}/update
    defaults: { _controller: "PMLibroBundle:Libro:update" }
    requirements: { _method: post|put }

libro_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PMLibroBundle:Libro:delete" }
    requirements: { _method: get|delete }
